models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    command: bash -c "mod_wsgi-express start-server --working-directory . --reload-on-changes /market/market/wsgi.py && python /market/manage.py makemigrations project2 && python /market/manage.py migrate"