models:
   image: djangorest
   external_links:
      - mysql:db
   ports:
      - "8001:8000"
   volumes:
      - .:/app
   stdin_open: true
   command: bash -c "python models/manage.py collectstatic --noinput > /dev/null && python models/manage.py makemigrations models_app && python models/manage.py migrate && python models/manage.py loaddata models/db.json && mod_wsgi-express start-server --working-directory models --url-alias /static market/market/static --reload-on-changes models/models/wsgi.py"

exp:
   image: djangorest
   links:
      - models:models-api
   ports:
      - "8002:8000"
   volumes:
      - .:/app
   stdin_open: true
   command: "mod_wsgi-express start-server --working-directory exp --reload-on-changes exp/exp/wsgi.py"

web:
   image: djangorest
   links:
      - exp:exp-api
   ports:
      - "8000:8000"
   volumes:
      - .:/app
   stdin_open: true
   command: bash -c "python web/manage.py collectstatic --noinput > /dev/null && mod_wsgi-express start-server --working-directory web --document-root web/build --reload-on-changes web/web/wsgi.py"